baseURL = "https://cotyped.github.io/blog/"
languageCode = "en-us"
title = "Cotyped | Î“"
theme="codex"
[params]
  github = "https://github.com/cotyped"
  iconTitles = ["GitHub"]

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "home"
  url = "/"